<div class="customer-data" data-bind="scope: 'section'">
    <h1 data-bind="text: customersection().msg"></h1>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "Assignment6_Customer/js/custom-section"
                    }
                }
            }
        }
    }
</script>
